name: ormir_xct
channels:
  - simpleitk
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - itkwidgets=0.32.0
  - numpy=1.23.3
  - pbr=5.4.2
  - pip=21.2.4
  - python=3.8.5
  - scikit-image=0.19.2
  - scipy=1.8.0
  - setuptools=52.0.0
  - simpleitk=2.0.2
  - vtk=9.0.1
  - pip:
    - itk==5.2.1
    - itk-core==5.2.1
    - itk-filtering==5.2.1
    - itk-io==5.2.1
    - itk-ioscanco==0.9.2
    - itk-numerics==5.2.1
    - itk-registration==5.2.1
    - itk-segmentation==5.2.1
    - notebook==6.5.2
    - numba==0.56.3
